### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by elsodev** [hootlex/laravel-friendships#9]
Hi, awesome package. just one thing

How do I do pagination when a user has a lot of friends.
```php
$user->getFriends()->paginate(20);
```

Thanks

**Comment by elsodev** [comment]
Hi, also is there away to limit getFriends() and the other methods too?
$user->getFriends(5);

```php
 public function getFriends($limit)
    {
        $friendships = $this->findFriendships(Status::ACCEPTED)->get(['sender_id', 'recipient_id']);
        $recipients = $friendships->lists('recipient_id')->all();
        $senders = $friendships->lists('sender_id')->all();

        return $this->where('id', '!=', $this->getKey())->whereIn('id', array_merge($recipients, $senders))->take($limit)->get();
    }
```

**Comment by hootlex** [comment]
Hello,

All the methods like `getFriends`, `getAcceptedFriendships`, etc. are based on `findFriendships` method which is a private method of `Friendable` trait.

If I make it public then you will be able to use:
```php
$user->findFriendships(Status::ACCEPTED)->paginate(20);
```

But you still wont be able to paginate `getFriends` method results, since it does not return a query builder but a collection of friends.

Let me know if this solves your problem. 

P.S. I may implement a pagination option for all methods in the future, but I dont have time at the moment. If you want to do it yourself I will be more than happy to accept your pr. :)

**Comment by elsodev** [comment]
@hootlex ok, i have made a pr. check it out.

**Comment by Tiaan1** [comment]
In Friendable.php find the following method `public function getFriends($perPage = 8)
    {
        if ($perPage == 0) {
            return $this->getFriendsQueryBuilder()->get();
        } else {
            return $this->getFriendsQueryBuilder()->paginate($perPage);
        }
    }`

and set the $perPage = amount you would like to paginate and call  `{{ $user->getFriends()->render() }}` on the page. i found that this is working for me :)
