### ISSUE TITLE
Laravel 5.5 support

### ISSUE THREAD

**Issue by rluders** [hootlex/laravel-friendships#91]
Hello.

Is there any hope for the Laravel 5.5 compliant package?

**Comment by nateritter** [comment]
@rluders I just tested it in L5.5 and it works fine. I did fork it (and change testing to use sqlite instead of mysql) here, if you're interested.  Everything passes: 

https://github.com/nateritter/laravel-friendships

https://travis-ci.org/nateritter/laravel-friendships
[![Build Status](https://travis-ci.org/nateritter/laravel-friendships.svg?branch=master)](https://travis-ci.org/nateritter/laravel-friendships)

**Comment by hootlex** [comment]
@nateritter good job! Could you submit a pr with the L5.5 tests?

**Comment by nateritter** [comment]
@hootlex actually, the tests work fine as-is with L5.5.  I just changed composer requirements.  I made some other changes, like using sqlite instead of mysql. Reduces a dependency on Travis, and tests are slightly faster.  If you want all that, I can just submit the PR with what I've got now?

**Comment by rluders** [comment]
@nateritter great. Do not forget about the package autodiscovery.

**Comment by nateritter** [comment]
@rluders Yup, all part of it.

**Comment by nateritter** [comment]
PR added: https://github.com/hootlex/laravel-friendships/pull/92

**Comment by hootlex** [comment]
Hey @nateritter, thanks for clarifying that it works fine as-is with 5.5. Since #92 is failing I'd rather stick with the current testing set up. Feel free to open a new pr if you think you can make the tests run faster. 🙂
